# Generated by Django 5.1.3 on 2024-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
